-- Migration: Allow 'comics' in watchlist.content_type check constraint
-- Generated by o3 assistant on 2025-06-30

-- Drop existing constraint if it exists
ALTER TABLE watchlist
  DROP CONSTRAINT IF EXISTS watchlist_content_type_check;

-- Recreate constraint with updated allowed values
ALTER TABLE watchlist
  ADD CONSTRAINT watchlist_content_type_check CHECK (content_type IN ('manga', 'comics')); 