-- Migration: create user_top_list table for per-user top manga/comic list (max 3)
-- Generated by o3 assistant on 2025-06-30

CREATE TABLE IF NOT EXISTS user_top_list (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  position INTEGER NOT NULL CHECK (position BETWEEN 1 AND 3),
  content_id UUID REFERENCES content(id) ON DELETE CASCADE,
  content_type TEXT NOT NULL CHECK (content_type IN ('manga', 'comics')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (user_id, position)
);

CREATE INDEX IF NOT EXISTS user_top_list_user_idx ON user_top_list(user_id); 